const styles = {
    container: 'container',
    header: 'header',
    headerWrapper: 'header-wrapper',
    logoWrapper: 'logo-wrapper',
    logo: 'logo',
    appCaption: 'app-caption',
    btn: 'btn',
    burger: 'burger',
    primary: 'primary',
    secondary: 'secondary',
    onlyicon: 'onlyicon',
    burgLine: 'burg-line',
    userPanel: 'user-panel',
    notification: 'notification',
    userData: 'user-data',
    avatar: 'avatar',
    userName: 'user-name',
};
