// eslint-disable-next-line no-unused-vars
const fakeTasks = [
    {
        id: '000001',
        name: 'Создать логотип приложения',
        description: 'Формат изображения – svg, размеры - 100х100px',
        createdAt: new Date('2023-03-11T23:00:00'),
        assignee: fakeUsers.find((user) => user.name === 'Иванов Иван').id,
        status: taskStatus.toDo,
        priority: 'High',
        isPrivate: false,
        author: fakeUsers.find((user) => user.name === 'Иванов Иван').id,
        comments: [],
    },
    {
        id: '000002',
        name: 'Переименовать константу DELAY_TIME',
        description: 'Необходимо переименовать константу с DELAY_TIME на DELAY_API_TIME',
        createdAt: new Date('2023-03-09T23:10:00'),
        assignee: fakeUsers.find((user) => user.name === 'Карэнт Йусер').id,
        author: fakeUsers.find((user) => user.name === 'Карэнт Йусер').id,
        status: taskStatus.toDo,
        priority: 'Medium',
        isPrivate: false,
        comments: [{
            id: '753958',
            text: 'Будет сделано!',
            createdAt: new Date('2023-03-09T23:00:05'),
            author: fakeUsers.find((user) => user.name === 'Карэнт Йусер').id,
        }],
    },
    {
        id: '000003',
        name: 'Подтереть комментарии в коде',
        description: 'Срочно нужно очистить код от комментов!!!',
        createdAt: new Date('2023-03-10T15:02:40'),
        assignee: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        author: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        status: taskStatus.inProgress,
        priority: 'High',
        isPrivate: false,
        comments: [{
            id: '868634',
            text: 'Уже бягу!',
            createdAt: new Date('2023-03-10T15:02:42'),
            author: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        }],
    },
    {
        id: '000004',
        name: 'Показать мидлу, где раки зимуют',
        description: 'Объяснить человеку как работать!',
        createdAt: new Date('2023-03-10T15:12:20'),
        assignee: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        author: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        status: taskStatus.toDo,
        priority: 'Low',
        isPrivate: true,
        comments: [],
    },
    {
        id: '000005',
        name: 'Написать фунцкию сортировки списков в списке списков.',
        description: 'Реализовать сортировку подмассивов в массивах.)',
        createdAt: new Date('2023-03-10T16:22:40'),
        assignee: fakeUsers.find((user) => user.name === 'Лида Тим').id,
        author: fakeUsers.find((user) => user.name === 'Лида Тим').id,
        status: taskStatus.toDo,
        priority: 'High',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000006',
        name: 'Поменять хэдэр с футтером!',
        description: 'Буквально. Поменять хэдэр и футтер местами!',
        createdAt: new Date('2023-03-10T16:47:13'),
        assignee: fakeUsers.find((user) => user.name === 'Йосиф Программилла').id,
        author: fakeUsers.find((user) => user.name === 'Йосиф Программилла').id,
        status: taskStatus.inProgress,
        priority: 'Medium',
        isPrivate: true,
        comments: [{
            id: '179842',
            text: 'А я бы так не делал...',
            createdAt: new Date('2023-03-10T16:51:17'),
            author: fakeUsers.find((user) => user.name === 'Йосиф Программилла').id,
        }],
    },
    {
        id: '000007',
        name: 'Изобрести необыкновенную кнопку!',
        description: 'Нужно сделать кнопку, которую пользователь не сможет проигнорировать.',
        createdAt: new Date('2023-03-11T00:07:10'),
        assignee: fakeUsers.find((user) => user.name === 'Игорёша').id,
        author: fakeUsers.find((user) => user.name === 'Игорёша').id,
        status: taskStatus.complete,
        priority: 'High',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000008',
        name: 'Сделать кнопку кликабельной.',
        description: 'Сделать кнопку, изобретенную Игорёшей, кликабельной и меняющей стиль!',
        createdAt: new Date('2023-03-12T15:14:52'),
        author: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        assignee: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        status: taskStatus.toDo,
        priority: 'Medium',
        isPrivate: false,
        comments: [{
            id: '976267',
            text: 'Фигней всякой заниматься! Придумайте задачу поинтересней!',
            createdAt: new Date('2023-03-12T16:26:59'),
            author: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        }],
    },
    {
        id: '000009',
        name: 'Добавить кнопке тенюшку.',
        description: 'Сделать кнопку, изобретенную Игорёшей, и менющей стиль благодаря Синьёру Пете, немного более естественной с тенями!',
        createdAt: new Date('2023-03-12T16:54:52'),
        assignee: fakeUsers.find((user) => user.name === 'Инна Катеринина').id,
        author: fakeUsers.find((user) => user.name === 'Инна Катеринина').id,
        status: taskStatus.toDo,
        priority: 'Low',
        isPrivate: false,
        comments: [{
            id: '348452',
            text: 'Это я могу запросто',
            createdAt: new Date('2023-03-17T05:06:19'),
            author: fakeUsers.find((user) => user.name === 'Инна Катеринина').id,
        }],
    },
    {
        id: '000010',
        name: 'Заказать пиццу на всех!',
        description: 'Необходимо накормить всю команду мегаразработчиков!!!',
        createdAt: new Date('2023-03-12T12:24:52'),
        assignee: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        author: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        status: taskStatus.inProgress,
        priority: 'High',
        isPrivate: false,
        comments: [{
            id: '643037',
            text: 'Какие брать?',
            createdAt: new Date('2023-03-12T12:24:53'),
            author: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        },
        {
            id: '590364',
            text: 'за веганскую!',
            createdAt: new Date('2023-03-12T12:24:55'),
            author: fakeUsers.find((user) => user.name === 'Инна Катеринина').id,
        },
        {
            id: '147390',
            text: 'Я как все',
            createdAt: new Date('2023-03-12T12:24:56'),
            author: fakeUsers.find((user) => user.name === 'Иванов Иван').id,
        },
        {
            id: '984920',
            text: 'Мне любую... Но ТРИ!',
            createdAt: new Date('2023-03-12T12:24:57'),
            author: fakeUsers.find((user) => user.name === 'Йосиф Программилла').id,
        },
        {
            id: '650371',
            text: 'А я сам съезжу! Инна гоу со мной!',
            createdAt: new Date('2023-03-12T12:24:59'),
            author: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        },
        ],
    },
    {
        id: '000011',
        name: 'Разработать сверхновый алгоритм блокчейнов.',
        description: 'Создать сверхновый, сверхбыстрый, сверхнадежный алгоритм работы блокчейна.',
        createdAt: new Date('2023-03-13T09:07:54'),
        author: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        assignee: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        status: taskStatus.toDo,
        priority: 'High',
        isPrivate: false,
        comments: [{
            id: '535812',
            text: 'Почему не мне интересная задача?! ТТ',
            createdAt: new Date('2023-03-17T10:21:19'),
            author: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        }],
    },
    {
        id: '000012',
        name: 'Почистить клавиатуру всем.',
        description: 'Пробежать всех и почистить им клавиатуры.',
        createdAt: new Date('2023-03-13T20:15:08'),
        assignee: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        author: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        status: taskStatus.toDo,
        priority: 'High',
        isPrivate: false,
        comments: [{
            id: '407615',
            text: 'Неее, я только что новый маник сдалала!',
            createdAt: new Date('2023-03-13T21:21:19'),
            author: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        }],
    },
    {
        id: '000013',
        name: 'Проверить домашку своего менти!',
        description: 'Проверить домашку и дать фидбэк!',
        createdAt: new Date('2023-03-14T08:00:02'),
        author: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        assignee: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        status: taskStatus.inProgress,
        priority: 'High',
        isPrivate: true,
        comments: [{
            id: '472605',
            text: 'ё-маё! совсем забыл!',
            createdAt: new Date('2023-03-14T23:28:51'),
            author: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        }],
    },
    {
        id: '000014',
        name: 'Изменить именование переменных во вем проекте!!!',
        description: 'Переделать все кебаб-кейс в кэмэл-кейсы! СРОЧНО!',
        createdAt: new Date('2023-03-15T01:10:07'),
        assignee: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        author: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        status: taskStatus.toDo,
        priority: 'High',
        isPrivate: true,
        comments: [],
    },
    {
        id: '000015',
        name: 'Уменьшить нагрузку на сервера прилаги!',
        description: 'Добавить еще пару нод в каждый кластер k8s\'a, иначе апишка от запросов лопнет.',
        createdAt: new Date('2023-03-15T04:54:22'),
        assignee: fakeUsers.find((user) => user.name === 'Игорёша').id,
        author: fakeUsers.find((user) => user.name === 'Игорёша').id,
        status: taskStatus.toDo,
        priority: 'Medium',
        isPrivate: true,
        comments: [{
            id: '658321',
            author: fakeUsers.find((user) => user.name === 'Игорёша').id,
            createdAt: new Date('2023-03-14T09:37:01'),
            text: 'Ребята, я ж не ДевОпс! Я только вчера на мидла сдал.',
        },
        {
            id: '784521',
            text: 'Сочувствую, чел. Придется разбираться...',
            createdAt: new Date('2023-03-14T13:42:17'),
            author: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        }],
    },
    {
        id: '000016',
        name: 'Подчистить старые коммиты и брэнчи!!!',
        description: 'Подчистить старые коммиты и брэнчи в системе хранения версий проекта.',
        createdAt: new Date('2023-03-15T08:13:51'),
        author: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        assignee: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        status: taskStatus.toDo,
        priority: 'Low',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000017',
        name: 'Сделать иконку приложения.',
        description: 'Сделать иконку приложения на основе логотипа.',
        createdAt: new Date('2023-03-15T09:26:43'),
        assignee: fakeUsers.find((user) => user.name === 'Игорёша').id,
        author: fakeUsers.find((user) => user.name === 'Игорёша').id,
        status: taskStatus.toDo,
        priority: 'Medium',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000018',
        name: 'Крестики для модалок!',
        description: 'Добавить модалкам крестики для закрытия!',
        createdAt: new Date('2023-03-15T11:39:23'),
        assignee: fakeUsers.find((user) => user.name === 'Йосиф Программилла').id,
        author: fakeUsers.find((user) => user.name === 'Йосиф Программилла').id,
        status: taskStatus.toDo,
        priority: 'Medium',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000019',
        name: 'Добавить подписи инпутам и контролам!',
        description: 'Добавить отсутствующие подписи инпутам',
        createdAt: new Date('2023-03-15T12:40:15'),
        author: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        assignee: fakeUsers.find((user) => user.name === 'Джун-Курьер').id,
        status: taskStatus.toDo,
        priority: 'Low',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000020',
        name: 'Добавить картинку на эррор-пэйдж!',
        description: 'Добавить картинку чтобы пользователь не так расстраивался',
        createdAt: new Date('2023-03-15T12:46:45'),
        assignee: fakeUsers.find((user) => user.name === 'Йосиф Программилла').id,
        author: fakeUsers.find((user) => user.name === 'Йосиф Программилла').id,
        status: taskStatus.toDo,
        priority: 'High',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000021',
        name: 'Изменить контраст на тоггл-барах!',
        description: 'Изменить контраст на тоггл-барах и добавить паддингов, чтобы били покрупнее.',
        createdAt: new Date('2023-03-15T13:16:16'),
        assignee: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        author: fakeUsers.find((user) => user.name === 'Константина Гон').id,
        status: taskStatus.toDo,
        priority: 'Medium',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000022',
        name: 'Сделать авторизацию модалкой!',
        description: 'Сделать модалкой, а не страницей. В соответствии с ТЗ',
        createdAt: new Date('2023-03-15T13:18:22'),
        assignee: fakeUsers.find((user) => user.name === 'Игорёша').id,
        author: fakeUsers.find((user) => user.name === 'Игорёша').id,
        status: taskStatus.toDo,
        priority: 'Medium',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000023',
        name: 'Реализовать основные методы для работы приложения!',
        description: 'В JavaScript файле создать массив для хранения списка задач. Заполнить массив объектами task (минимум 20 задач).',
        createdAt: new Date('2023-03-15T14:44:42'),
        author: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        assignee: fakeUsers.find((user) => user.name === 'Синьёр Петя').id,
        status: taskStatus.toDo,
        priority: 'Medium',
        isPrivate: false,
        comments: [],
    },
    {
        id: '000024',
        name: 'Добавить задачу в таск менеджер.',
        description: 'Придумать любую задачу и попробовать добавить ее к существующим.',
        createdAt: new Date('2023-03-03T13:27:42'),
        assignee: fakeUsers.find((user) => user.name === 'Карэнт Йусер').id,
        author: fakeUsers.find((user) => user.name === 'Карэнт Йусер').id,
        status: taskStatus.inProgress,
        priority: 'Medium',
        isPrivate: false,
        comments: [],
    },
];
