const styles = {
    container: 'container',
    link: 'link',
    brBar: 'br-bar',

    header: 'header',
    headerWrapper: 'header-wrapper',
    logoWrapper: 'logo-wrapper',
    logo: 'logo',
    appCaption: 'app-caption',

    main: 'main',

    btn: 'btn',
    btnCaption: 'btn-caption',
    burger: 'burger',
    primary: 'primary',
    secondary: 'secondary',
    onlyicon: 'onlyicon',
    burgLine: 'burg-line',
    btnGroup: 'btn-group',
    hprio: 'hprio',
    mprio: 'mprio',
    lprio: 'lprio',
    active: 'active',

    userPanel: 'user-panel',
    notification: 'notification',
    userData: 'user-data',
    avatar: 'avatar',
    userName: 'user-name',
    userDate: 'user-date',

    actionBar: 'action-bar',
    barGroup: 'bar-group',

    activeFilters: 'active-filters',
    filterBadge: 'filter-badge',
    text: 'text',
    textarea: 'textarea',

    boardWrapper: 'board-wrapper',
    taskboard: 'taskboard',
    asTable: 'as-table',
    taskboardHeader: 'taskboard-header',
    taskboardCaption: 'taskboard-caption',
    taskboardContent: 'taskboard-content',

    taskContainer: 'task-container',
    task: 'task',
    taskHeader: 'task-header',
    taskInfo: 'task-info',
    taskComments: 'task-comments',
    taskTitle: 'task-title',
    taskDescription: 'task-description',
    taskCaption: 'task-caption',
    taskPanel: 'task-panel',
    taskActions: 'task-actions',

    userinfo: 'userinfo',
    userinfoData: 'userinfo-data',

    badge: 'badge',

    hPriority: 'h-priority',
    mPriority: 'm-priority',
    lPriority: 'l-priority',

    inprogressTask: 'inprogress-task',
    completeTask: 'complete-task',

    inp: 'inp',
    inpCaption: 'inp-caption',
    sel: 'sel',
    border: 'border',
    wrong: 'wrong',

    taskFilter: 'task-filter',
    close: 'close',

    blurWrapper: 'blur-wrapper',
    fieldContainer: 'field-container',
    fieldCaption: 'field-caption',
    filled: 'filled',

    commentsSection: 'comments-section',
    commentsContainer: 'comments-container',
    userComment: 'user-comment',
    commentText: 'comment-text',
    spoiler: 'spoiler',
    textInfo: 'text-info',

    regForm: 'reg-form',
    controlBlock: 'control-block',
    selectedImage: 'selected-image',
    imageFrame: 'image-frame',
    btnBlock: 'btn-block',
    emptyAvatar: 'empty-avatar',

    wrapperShortInfo: 'wrapper-short-info',
    fullInfo: 'full-info',
    todoType: 'todo-type',

    notificationBox: 'notification-box',
    hidden: 'hidden',
    hide: 'hide',
    notifly: 'notifly',
    errNoti: 'err-noti',
    warnNoti: 'warn-noti',
    infoNoti: 'info-noti',
    succNoti: 'succ-noti',
    focusSucc: 'focus-succ',
    focusInfo: 'focus-Info',
    focusErr: 'focus-err',
    focusWarn: 'focus-warn',

    footer: 'footer',
    footerWrapper: 'footer-wrapper',
    appName: 'app-name',
    caption: 'caption',
    version: 'version',
    contact: 'contact',
    copyright: 'copyright',
    mailTo: 'mailto',

    ico: 'ico',
    icons: {
        idelete: 'idelete',
        iedit: 'iedit',
        iexpand: 'iexpand',
        icomment: 'icomment',
        isearch: 'isearch',
        iaddTask: 'iadd-task',
        ifilter: 'ifilter',
        iprivateLock: 'iprivate-lock',
        ipublicEarth: 'ipublic-earth',
        iaddCircle: 'iadd-circle,',
        iarrowLeft: 'iarrow-left',
        iarrowRight: 'iarrow-right',
        iavatar: 'iavatar',
        iclear: 'iclear',
        iclose: 'iclose',
        idateTime: 'idate-time',
        idotFill: 'idot-fill',
        iexit: 'iexit',
        ieyeSlash: 'ieye-slash',
        imoon: 'imoon',
        imailto: 'mailto',
        isun: 'isun',
        iviewHorizontal: 'iview-horizontal',
        iviewVertical: 'iview-vertical',
    },
};
